### ISSUE TITLE
Cannot drag the tweez window

### ISSUE THREAD

**Issue by Robles1969** [mike-ward/tweetz-desktop#12]
This has happened from long time now. The window cannot be dragged and sometimes can barely be resized. Many times the cursor simply won't pick the border to change the position or size... any sugestion.

Using W10 64 bits, happens in all my Pcs

**Comment by mike-ward** [comment]
You'll need to turn on the "Show Window Contents while Dragging" option:

https://www.isunshare.com/windows-10/show-or-hide-window-contents-while-dragging-in-windows-10.html

**Comment by Robles1969** [comment]
Thanks man... funny stuff, it was ticked, but it did not  work, so I
unticked and ticked back and begun working.

Thanks again, great work, the best client for Twitter ever, I have used for
many years.

Regards,

Alfonso

2017-07-11 8:58 GMT-04:00 Mike Ward <notifications@github.com>:
