### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by sarcinelli86** [mike-ward/tweetz-desktop#16]
Since the last Windows 10 update (KB4051963 - OS Build 16299.98) I can't get Tweetz to work, it instantly crashes every time I try to run it.

**Comment by mike-ward** [comment]
I'm running 16299.64 here. We'll keep an eye on it and see if anyone else has issues.

**Comment by sarcinelli86** [comment]
Ok, found the culprit.
The problem was RivaTuner, once I added a profile for tweetz.exe and set the application detection level to "none" the problem was solved.
