### ISSUE TITLE
Tweetz window fixed on left side of screen, would like to move

### ISSUE THREAD

**Issue by Sweepr** [mike-ward/tweetz-desktop#17]
Tweetz window fixed on left side of screen, would like to move in a different position, like the rightside?

Thanks.

**Comment by sinistra** [comment]
Somehow solved .

**Comment by mike-ward** [comment]
This http://mike-ward.net/2015/01/21/unable-move-tweetz-resolved/ may help

**Comment by Sweepr** [comment]
Thanks for the comment, somehow after a reboot I was able to move the window.

So this could be closed..  Thanks again for the great software!
