### ISSUE TITLE
Tweetz seems to send a Down-Arrow code to currently active window

### ISSUE THREAD

**Issue by OSHChip-Owner** [mike-ward/tweetz-desktop#18]
Issue only seen in a browser based email reader and a game.

Tweetz seems to send a Down-Arrow code to the currently active window whenever a new tweet arrives, but only for certain programs.

For example, in my browser (Chrome) based email reader, if the focus is on the message list, with a message highlighted, and the browser is the active window, when a new tweet arrives, the next message in the list is highlighted. I can replicate this by typing the physical Down-Arrow key. Same for the game that is also affected.

Unfortunately, for debugging this, I don't see this in any other programs. For example, my text editor Ultraedit (or notepad) do not react this way. The same browser based email reader viewed with Microsoft Internet Explorer also does not have the problem (and coincidentally does not respond to the  Down-Arrow key)

So to see the problem, the focus must be on either the game (Sudoku Master), or Chrome running my browser based email reader.

The browser based email reader https://webmail.hosting.earthlink.net/#/mail/list/msg  , but without an account, you probably can't replicate the problem I am reporting.

Having typed the above, this seems like such a niche corner case, it is probably not worth the effort to track it down.

**Comment by mike-ward** [comment]
Tweetz does not actively hook the keyboard or other access other system level hooks. It's weird behavior but I can't see how a program could do this unintentionally.
