### ISSUE TITLE
Stuck on desktop

### ISSUE THREAD

**Issue by timcin** [mike-ward/tweetz-desktop#19]
I normally keep my Tweetz desktop on the lower right side of my screen. I just upgraded my Tweetz to 1.3.2 and when it relaunched it appeared on the top left side of my screen. If I try to move it the program snaps right back to the same spot. I thought something may have corrupted so I completely uninstalled the program and installed 1.3.2. The same thing happens, it's stuck to the left side of the screen.
How do I fix this?

timcin

**Comment by mike-ward** [comment]
See https://mike-ward.net/2015/01/21/unable-move-tweetz-resolved/
