### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by tinyrobit** [mike-ward/tweetz-desktop#20]
just updated from 1.2.4 to 1.3.3 on windows 7 and when i first clicked on an image it told me i needed WMP10 installed, so i installed it an clicked an image and it opened fine. i then clicked a video clip in a tweet and the video popped up but only played 1 frame then stopped and hanged and cpu usage went up to 13% for tweetz and stayed there till i closed tweetz. if i close the video popup and try an click either a picture or video i get no popup anymore an cpu usage for tweetz stays at 13% till i restart tweetz. this 1 frame then hangin happens anytime i try and open a video clip, pictures work fine.

**Comment by mike-ward** [comment]
Can you send me a link to the tweet?

**Comment by tinyrobit** [comment]
Any tweet with video doesnt work like this [one](https://twitter.com/PlayStation/status/1064269515305836544)
 
Also some [videos](https://twitter.com/MegBucher/status/1064272513297870848) but not all give the below error, mabey cause its tagged as sensitive material?
![untitled](https://user-images.githubusercontent.com/41088908/48679243-d0bc9e00-eb85-11e8-9e9d-f90abf56a113.jpg)

**Comment by mike-ward** [comment]
Well, it's working on Windows 10 here. Maybe it's a Windows 7 thing.

**Comment by CollinChaffin** [comment]
Is Windows 7 not supported for this client?

**Comment by tinyrobit** [comment]
im using 1.2.4 its the last version to work without error on win 7. i wish the latest would work on win 7 tho :(

**Comment by mike-ward** [comment]
I don't support Windows 7. Sorry.
