### ISSUE TITLE
Images don't open

### ISSUE THREAD

**Issue by ferenczy** [mike-ward/tweetz-desktop#21]
It often happens that after I open a few images or maybe simply after some time Tweetz is running, it **stops opening images when I click them**. The cursor still changes to hand when I hover them, but click simply does nothing. It starts to work again when I restart Tweetz.

It's happening for several versions already.

Tweetz version: 1.3.3
Windows 7 Ultimate 64-bit

**Comment by mike-ward** [comment]
It's a feature. User requested.

Windows 7 not supported.
