### ISSUE TITLE
User settings are corrupted

### ISSUE THREAD

**Issue by DigNative** [mike-ward/tweetz-desktop#3]
Hi,

I experience some trouble using the latest version of Tweetz Desktop: I always get the message, that my user settings are corrupted. Additionally, I receive the following execption:

    ---------------------------

    ---------------------------
    Tweetz Desktop Crash Report

    Date: 2015-03-05 18:56:58Z

    Version: 0.8.23

    -----------------------------------------------------------------

    *** Pressing Ctrl+C will copy the contents of this dialog ***

    *** Email to: mike@mike-ward.net ***

    -----------------------------------------------------------------

    Operation System Information

    -----------------------------------------------------------------

    Windows 7 Professional

    Service Pack: Service Pack 1

    Exception

    -----------------------------------------------------------------

    System.InvalidCastException: Das Objekt des Typs "System.Xml.XmlException" kann nicht in Typ "System.Configuration.ConfigurationException" umgewandelt werden.

       bei tweetz5.App.ApplicationStart(Object sender, StartupEventArgs e) in c:\Users\Mike\Documents\GitHub\tweetz-desktop\tweetz\tweetz5\App.xaml.cs:Zeile 31.

       bei System.Windows.Application.OnStartup(StartupEventArgs e)

       bei System.Windows.Application.<.ctor>b__1(Object unused)

       bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

       bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

    ---------------------------
    OK   
    ---------------------------

**Comment by mike-ward** [comment]
I have not been able to determine why this happens. You can delete the settings files at `/Users/your_username/AppData/local/Mike-Ward.Net`

**Comment by DigNative** [comment]
Thank you for your fast answer. After deletion of the settings folder, everything works now again as expected.
