### ISSUE TITLE
Unable to resize 1.3.4

### ISSUE THREAD

**Issue by gryphonshafer** [mike-ward/tweetz-desktop#30]
I recently had what seemed like an API error with version 1.3.3, so I upgraded to 1.3.4, which resolved the previous error. However, I'm now unable to resize the app. I can move it around, and hovering over the edge changes the cursor to a resize cursor, but click-and-drag doesn't change the size of the app. I've tried a variety of different attempts, a few restarts along the way, but no success.

**Comment by gryphonshafer** [comment]
As a short-term fix: Where is the height property stored? I could just hack that to get the size I want. Thanks much.

**Comment by qijianjun** [comment]
I can resize it.

**Comment by JJBode** [comment]
I only can resize it on my Full HD Display. On my HighRes displays (2560 x 1440 and 4K (3840 x 2160)) it is not possible to resize Tweetz at all, only moving works. I have this problem in v1.3.3 and in 1.3.4.

**Comment by mike-ward** [comment]
If you reinstall 1.3.3 can you resize? For the record, it works fine on my 3440 x 1440 screen. The sizing border is only on pixel wide so it can require some dexterity hit the mark.

**Comment by gryphonshafer** [comment]
OK, so this is very strange. I uninstalled 1.3.4 and installed 1.3.3. The API failure returned, as expected. Ignoring that, I tried to resize the app. Just like in 1.3.4, I was able to position the cursor over the top edge such that it would change to a resize icon. Clicking-and-dragging worked (with 1.3.3), but with a big exception: I could only shrink the size of the app. I could not increase the size of the app. I tried a variety of different times, each time only being able to shrink the size of the app. Once shrunk down to its minimum size, I was no longer able to resize the app at all.

**Comment by gryphonshafer** [comment]
I've tested resizing in all versions going back to 1.2, and the app behaves the same way. Resize works to shrink the height but not to increase the height. Resizing worked in the past for me, I'm sure. So I believe this is not a problem specifically with 1.3.4 but likely is something to do with a Windows 10 update that's impacting only this app.

**Comment by JJBode** [comment]
Indeed shrinking is the only form of resizing that works. I have exactly the same experience as Graphon Shafer describes.

 

Before reinstalling 1.3.3 I completely removed 1.3.4 but it made no difference at all. Still, on my FHD display I can resize horizontal, vertical, etc. I agree with Gryphon Shafer that it can be a problem in Windows 10, perhaps the latest release (1903). However, it can also have to do something with scaling (not the strongest feature in Windows as averybody knows). Because on my FHD screen I don’t scale (stays 100%) and on the other displays I do. That’s the only difference.

 

Van: Mike Ward <notifications@github.com> 
Verzonden: woensdag 31 juli 2019 14:47
Aan: mike-ward/tweetz-desktop <tweetz-desktop@noreply.github.com>
CC: JJBode <jeroen@bodesteyn.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [mike-ward/tweetz-desktop] Unable to resize 1.3.4 (#30)

 

If you reinstall 1.3.3 can you resize? For the record, it works fine on my 3440 x 1440 screen. The sizing border is only on pixel wide so it can require some dexterity hit the mark.

**Comment by norsehealer** [comment]
I'm unable to resize via the right-hand side of the program, but the bottom and left-hand side work fine.

**Comment by iparish** [comment]
Not sure this is helpful but I can't resize this either. Windows 10. I can make Tweetz shorter (reduce height) from bottom resizing bar but I can't make it taller.

**Comment by gryphonshafer** [comment]
Where is the height property stored? I could just hack that to get the size I want.

**Comment by utahbmxer** [comment]
I have this same issue.  Sad, as now this app is near useless to me.  I can't even see an entire tweet now.  Looked in the config, doesn't seem that there is a height setting?  Have turned all windows performance settings on/off, as I noticed the 'show window contents while dragging' must be enabled to move the window, so suspected a related bug, but no avail.

**Comment by mike-ward** [comment]
Windows just updated on my laptop and now I'm broken to. This means something changed outside of Tweetz. I did a quick debug and found the window no longer receives mouse messages when sizing larger. Not much I can do if I don't get a message. WPF and window sizing has always been a CF. Even newly created apps behave oddly when sizing larger (they don't show feedback but resize once the mouse is released).

I don't have a solution for an issue like this. 

You can find settings in C:\Users\<user>\AppData\Local\Mike-Ward.Net and edit them there.

I've seen others report this issue for WPF apps recently so I have to think it will get "magically" fixed at some point.

**Comment by utahbmxer** [comment]
Thanks, Mike.   I would agree that window sizing in WPF is a CF.  Everytime I enlarge a window it's always transparent, even MS provided apps.  Go figure.

What value do we need to add/update to expand the height?  I see a "length" but it keeps setting back to 44 every time I close the app down.  Maybe that is not the window length, but something else.  I tried looking through the code, but I was at work and short on time.

Thanks again for your all your work.  Much appreciated.

**Comment by iparish** [comment]
If you edit top and bottom numbers within in the config file it will change the height of the window.
<normalPosition>
                            <Left>1712</Left>
                            <Top>8</Top>
                            <Right>1912</Right>
                            <Bottom>1020</Bottom>

**Comment by mike-ward** [comment]
@iparish That's correct. The API used is SetWindowPosition which has this wonky structure. For all the work MS puts into their App model for WPF you would think they would have a simple property like "Remember Window Position" instead of relying on some 30 year old API and Interop.
