### ISSUE TITLE
Retweets still appearing when disabled for a user

### ISSUE THREAD

**Issue by dracan** [mike-ward/tweetz-desktop#4]
Turning off retweets of users' that you're following in Twitter doesn't seem to have any affect - those retweets are still appearing in the timeline.

Ps. Awesome app btw :)

**Comment by mike-ward** [comment]
Thanks for the bug report.

Yeah, that's a known problem. The twitter API does not honor the setting and returns those tweets anyways. Same goes for many of the other notifications A real bummer and another example of how twitter is hostile to third party apps.
