### ISSUE TITLE
Show the most recent tweets by a user

### ISSUE THREAD

**Issue by evaryont** [mike-ward/tweetz-desktop#8]
I'm liking tweetz a lot right now, but one thing I've run into that I would like to see is the ability to show an account's recent tweets. Not sure how you feel about adding this complexity, there would need to be additional UI to distinguish the normal timeline vs a particular account's timeline. UX-wise, I imagine the easiest way to enter this UI would be to make the tweet count in the profile summary clickable.

**Comment by mike-ward** [comment]
It's an interesting idea. You can click on the tweet id in the user profile which goes to the users twitter home page where you see the recent tweets. Not as elegant but it gets the job done.
